// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8RhQuxBhMIWdBcIc2jh6URuANx6lJr0',
    appId: '1:1022831872618:web:a643c13aacaff32b98d813',
    messagingSenderId: '1022831872618',
    projectId: 'openrooms-bee8a',
    authDomain: 'openrooms-bee8a.firebaseapp.com',
    databaseURL: 'https://openrooms-bee8a-default-rtdb.firebaseio.com',
    storageBucket: 'openrooms-bee8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9yLpdH5EhZL2FehrUz8c5fXje0xu8xOM',
    appId: '1:1022831872618:android:c6c46916b0fda65598d813',
    messagingSenderId: '1022831872618',
    projectId: 'openrooms-bee8a',
    databaseURL: 'https://openrooms-bee8a-default-rtdb.firebaseio.com',
    storageBucket: 'openrooms-bee8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbO7iQGrKnuDV5yokRqULFz6BAiHimTaM',
    appId: '1:1022831872618:ios:1e7ab506edb422e198d813',
    messagingSenderId: '1022831872618',
    projectId: 'openrooms-bee8a',
    databaseURL: 'https://openrooms-bee8a-default-rtdb.firebaseio.com',
    storageBucket: 'openrooms-bee8a.appspot.com',
    iosBundleId: 'com.example.openrooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbO7iQGrKnuDV5yokRqULFz6BAiHimTaM',
    appId: '1:1022831872618:ios:e4848362540817ad98d813',
    messagingSenderId: '1022831872618',
    projectId: 'openrooms-bee8a',
    databaseURL: 'https://openrooms-bee8a-default-rtdb.firebaseio.com',
    storageBucket: 'openrooms-bee8a.appspot.com',
    iosBundleId: 'com.example.openrooms.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8RhQuxBhMIWdBcIc2jh6URuANx6lJr0',
    appId: '1:1022831872618:web:4059d856938e94d798d813',
    messagingSenderId: '1022831872618',
    projectId: 'openrooms-bee8a',
    authDomain: 'openrooms-bee8a.firebaseapp.com',
    databaseURL: 'https://openrooms-bee8a-default-rtdb.firebaseio.com',
    storageBucket: 'openrooms-bee8a.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAQ8RhQuxBhMIWdBcIc2jh6URuANx6lJr0',
    appId: '1:1022831872618:web:e534bf1fc4f27dab98d813',
    messagingSenderId: '1022831872618',
    projectId: 'openrooms-bee8a',
    authDomain: 'openrooms-bee8a.firebaseapp.com',
    databaseURL: 'https://openrooms-bee8a-default-rtdb.firebaseio.com',
    storageBucket: 'openrooms-bee8a.appspot.com',
  );
}
